<div
  data-live2-embed="1"
  data-live2-picked-up="0"
  data-live2-loaded="0"
  data-live2-embed-id="<?php echo $block->getData('embed_id'); ?>"
  data-live2-team-id="65b8e3a8885468de58b7c862" 
>
  <div class="live2-container"></div>
  <div class="live2-custom-css" style="display: none !important"></div>
</div>



<script src="https://storage.googleapis.com/uploads-live2ai-dev/assets/sdk/dev/live2ai-embed-sdk.js?v=3"></script>